vk:
  accessToken: vk1.a.B1WFpS5isKADqV-CiNyOafTAaXi1dVXxLeKzyWcXMuFaWIdV0x_lS9ncJghUDUiXbhcfCv8Ap7Fx6jE_1JgchKv2Kmnx2Xw5KOn30YpHJtfv4kw0KwvYSrYQR9x4XEwT5ibouXs7XYbD3PbqaTMRKnM2WN7bJkssIsgPzaIi4goOxzkcF7esSZ0gU97dKUXyUA9nH8q-tuMunsO881VGCw
  urlGroup: https://vk.com/club226052312
server:
  port: 8080
