services:
  postgres:
    image: postgres:13.2-alpine
    container_name: banking
    restart: always
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql