services:
  postgres:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_DB: transactions
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  spring:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres